### PR TITLE
Add a new demo and fixed an import bug

### PR DESCRIPTION
**Pull request by xinglong-li**
This PR:
* Reimplement the example in the notebook 
  https://github.com/probml/pyprobml/blob/master/notebooks/book2/29/causal_impact.ipynb

* Fix an import bug of the sts components.
  Note that the command ```from sts_components import *```  in the initial version of the file 'sts_model.py' is crucial so 
  that users can use any component in the file 'sts_components.py' without loading this file (and we don't want the user 
  to load it).

### CODE REVIEW

**Comment by murphyk** [comment]
In general it is considered bad style to do things like `from sts_components import *` outside of a notebook, but I'll let this go for now.

**Comment by juanitorduz** [comment]
hey! I worked on the changes regarding the `import *` which raises a flake8 error (it is indeed not recommended). The CI is failing because of this. Do you want me to try to fix it?

**Comment by juanitorduz** [comment]
I was also working on the pre-commit hooks in https://github.com/probml/sts-jax/pull/9 ... maybe we want to sync these efforts to use the mode the ci checks in the development workflow :)

**Comment by murphyk** [comment]
I didn't know that Xinglong's PR broke things, I just thought it was bad style.
Maybe we should just omit flake8?

**Comment by juanitorduz** [comment]
Ok! I'll work on it :)

**Pull request merged**
